import {
  SET_ORIGIN,
  SET_DESTINATION,
  INITIATE_FETCH_PORT,
  SUCESS_FETCH_PORT,
  FAILURE_FETCH_PORT
} from "./ports-actions";

import {
  INITIATE_FETCH_MARKET,
  SUCESS_FETCH_MARKET,
  FAILURE_FETCH_MARKET
} from "./market-actions";

const RESET_STATE = "RESET_STATE";

export {
  RESET_STATE,
  SET_ORIGIN,
  SET_DESTINATION,
  INITIATE_FETCH_PORT,
  SUCESS_FETCH_PORT,
  FAILURE_FETCH_PORT,
  INITIATE_FETCH_MARKET,
  SUCESS_FETCH_MARKET,
  FAILURE_FETCH_MARKET
};
