export const SET_DESTINATION = "SET_DESTINATION";
export const SET_ORIGIN = "SET_ORIGIN";
export const INITIATE_FETCH_PORT = "INITIATE_FETCH_PORT";
export const SUCESS_FETCH_PORT = "SUCESS_FETCH_PORT";
export const FAILURE_FETCH_PORT = "FAILURE_FETCH_PORT";
